### ISSUE TITLE
Register Restless API for <class 'flangular.computer.Computer'> @ computer

### ISSUE THREAD

**Issue by giancarlocp** [uvc-ingenieure/flangular#1]
Downloaded and executed without changes.

```
$ py server.py
Register Restless API for <class 'flangular.computer.Computer'> @ computer
../venv/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py:173: SAWarning: Unmanaged access of declarative attribute __tablename__ from non-mapped class Computer
  (desc.fget.__name__, cls.__name__))
Traceback (most recent call last):
  File "server.py", line 3, in <module>
    from flangular import app
  File "../flangular/flangular/__init__.py", line 11, in <module>
    import computer
  File "../flangular/flangular/computer.py", line 4, in <module>
    class Computer(Model):
  File "../flangular/flangular/model.py", line 15, in __new__
    model.register()
  File "../flangular/flangular/model.py", line 37, in register
    collection_name=cls.__url__)
  File "../venv/local/lib/python2.7/site-packages/flask_restless/manager.py", line 566, in create_api_blueprint
    pk_name = primary_key or primary_key_name(model)
  File "../venv/local/lib/python2.7/site-packages/flask_restless/helpers.py", line 233, in primary_key_name
    return 'id' if 'id' in pk_names else pk_names[0]
IndexError: list index out of range
```

**Comment by mholtzberg** [comment]
On which platform?
I just tried on kubuntu 14.04 and it works.

**Comment by giancarlocp** [comment]
ubu 14.04 and it's working, the problem was:

```
Flask-Restless (0.17.0)
Flask-SQLAlchemy (2.0)
```

instead

```
Flask-Restless (0.15.1)
Flask-SQLAlchemy (0.16)
```
